# https://docs.renovatebot.com/modules/manager/mise/#additional-information
[tools]
# https://gitleaks.io/
gitleaks = "8.30.0"
# https://pre-commit.com/
pre-commit = "4.5.0"
# https://taskfile.dev/
task = "3.41.0"
